# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Neroli
env:
  PROJECT_NAME: Neroli
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-neroli-static:
    runs-on: self-hosted

    steps:
      - name: Clone $PROJECT_NAME repository
        uses: actions/checkout@v3
      - name: Install all depedencies
        run: npm install
      - name: Build $PROJECT_NAME project
        run: npm run build
      - name: Copy $PROJECT_NAME build to nginx static serve
        run: sudo cp -r dist/lieblings /var/www/nerolicosmetic.com/
