# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Neroli
env:
  PROJECT_NAME: Neroli
  BUILD_SOURCE: dist/lieblings
  BUILD_TARGET: /var/www/nerolicosmetic.com/
on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-static:
    runs-on: self-hosted

    steps:
      - name: Clone ${{ env.PROJECT_NAME }} repository
        uses: actions/checkout@v3
      - name: Install all depedencies
        run: npm install
      - name: Build ${{ env.PROJECT_NAME }}
        run: npm run build
      - name: Copy build folder ${{ env.BUILD_SOURCE }} to ${{ env.BUILD_TARGET }}
        run: sudo cp -r ${{ env.BUILD_SOURCE }} ${{ env.BUILD_TARGET }}
